name: Update a WordPress readme.txt's Test up to value to the lastest release of WordPress.

on:
  push:
    branches: [ "main" ]
    paths: [ "readme.txt" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: bash ${GITHUB_WORKSPACE}/.github/workflows/update-wp-tested-up-to.sh
      env:
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}